# Generated by Django 3.0.3 on 2020-04-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200309_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(default=None, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_video',
            field=models.URLField(default=None),
        ),
    ]
