# Generated by Django 3.0.3 on 2020-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200408_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_video',
            field=models.URLField(null=True),
        ),
    ]
