# Generated by Django 3.0.3 on 2020-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200408_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, default=None, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_video',
            field=models.URLField(blank=True, default=None),
        ),
    ]
